"""Validation of Dota2ProTracker builds exported from its browser collector."""

from __future__ import annotations

import json
from collections.abc import Mapping
from math import isfinite
from pathlib import Path
from typing import Any

from tools.stratz_collector.__main__ import _atomic_json_write
from tools.stratz_collector.aggregate import DataShapeError


HERO_IDS = frozenset({
    1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20,
    21, 22, 23, 25, 26, 27, 28, 29, 30, 31, 32, 33, 34, 35, 36, 37, 38, 39,
    40, 41, 42, 43, 44, 45, 46, 47, 48, 49, 50, 51, 52, 53, 54, 55, 56, 57,
    58, 59, 60, 61, 62, 63, 64, 65, 66, 67, 68, 69, 70, 71, 72, 73, 74, 75,
    76, 77, 78, 79, 80, 81, 82, 83, 84, 85, 86, 87, 88, 89, 90, 91, 92, 93,
    94, 95, 96, 97, 98, 99, 100, 101, 102, 103, 104, 105, 106, 107, 108,
    109, 110, 111, 112, 113, 114, 119, 120, 121, 123, 126, 128, 129, 131,
    135, 136, 137, 138, 145, 155,
})
POSITIONS = frozenset({"pos%201", "pos%202", "pos%203", "pos%204", "pos%205"})
REQUIRED_FIELDS = (
    "num_matches", "num_wins", "win_rate", "abilities", "talents", "items_mid_late",
    "anchor_items", "sixslot", "neutral_stats", "starting_items", "anchor_build_matches",
)
MIN_POPULATED_HEROES = 100
MIN_POPULATED_POSITIONS = 400
MAX_TOTAL_MATCH_DELTA = 0.25


def _integer(value: Any, *, field: str, hero_id: int, position: str) -> int:
    try:
        parsed = int(value)
    except (TypeError, ValueError) as exc:
        raise DataShapeError(f"{field} for hero {hero_id}, {position} must be an integer") from exc
    if parsed < 0:
        raise DataShapeError(f"{field} for hero {hero_id}, {position} must not be negative")
    return parsed


def validate_builds(raw: Any) -> dict[str, dict[str, dict[str, Any]]]:
    """Validate the format generated by the existing D2PT browser script."""
    if not isinstance(raw, Mapping):
        raise DataShapeError("D2PT export root must be an object")
    try:
        actual_ids = {int(hero_id) for hero_id in raw}
    except (TypeError, ValueError) as exc:
        raise DataShapeError("D2PT export has a non-numeric hero id") from exc
    if actual_ids != HERO_IDS:
        raise DataShapeError(
            f"D2PT hero set differs; missing={sorted(HERO_IDS - actual_ids)}, "
            f"extra={sorted(actual_ids - HERO_IDS)}"
        )

    populated_heroes = 0
    populated_positions = 0
    result: dict[str, dict[str, dict[str, Any]]] = {}
    for hero_id in sorted(HERO_IDS):
        raw_positions = raw.get(str(hero_id))
        if not isinstance(raw_positions, Mapping):
            raise DataShapeError(f"D2PT hero {hero_id} must be an object")
        unknown_positions = set(raw_positions) - POSITIONS
        if unknown_positions:
            raise DataShapeError(f"D2PT hero {hero_id} has unknown positions: {sorted(unknown_positions)}")
        result[str(hero_id)] = {}
        for position, build in raw_positions.items():
            if not isinstance(build, Mapping):
                raise DataShapeError(f"D2PT build for hero {hero_id}, {position} must be an object")
            missing = [field for field in REQUIRED_FIELDS if field not in build]
            if missing:
                raise DataShapeError(f"D2PT build for hero {hero_id}, {position} misses {missing}")
            matches = _integer(build["num_matches"], field="num_matches", hero_id=hero_id, position=position)
            wins = _integer(build["num_wins"], field="num_wins", hero_id=hero_id, position=position)
            if wins > matches:
                raise DataShapeError(f"num_wins exceeds num_matches for hero {hero_id}, {position}")
            try:
                win_rate = float(build["win_rate"])
            except (TypeError, ValueError) as exc:
                raise DataShapeError(f"win_rate for hero {hero_id}, {position} must be numeric") from exc
            if not isfinite(win_rate) or not 0 <= win_rate <= 1:
                raise DataShapeError(f"win_rate for hero {hero_id}, {position} is out of range")
            if matches and abs(win_rate - wins / matches) > 1e-8:
                raise DataShapeError(f"win_rate for hero {hero_id}, {position} disagrees with wins")
            result[str(hero_id)][position] = dict(build)
            populated_positions += 1
        if result[str(hero_id)]:
            populated_heroes += 1
    if populated_heroes < MIN_POPULATED_HEROES:
        raise DataShapeError(
            "D2PT export has too few populated heroes: "
            f"{populated_heroes} (minimum {MIN_POPULATED_HEROES})"
        )
    if populated_positions < MIN_POPULATED_POSITIONS:
        raise DataShapeError(
            "D2PT export has too few populated positions: "
            f"{populated_positions} (minimum {MIN_POPULATED_POSITIONS})"
        )
    return result


def _total_matches(builds: Mapping[str, Mapping[str, Mapping[str, Any]]]) -> int:
    return sum(
        int(build["num_matches"])
        for positions in builds.values() for build in positions.values()
    )


def import_d2pt_builds(
    *, source: Path, reference: Path, output: Path,
    max_total_match_delta: float = MAX_TOTAL_MATCH_DELTA,
) -> dict[str, int | float]:
    """Validate a browser-exported file and save it as a collector artifact."""
    if not 0 <= max_total_match_delta < 1:
        raise ValueError("max_total_match_delta must be in [0, 1)")
    try:
        raw = json.loads(source.read_text(encoding="utf-8"))
    except (OSError, json.JSONDecodeError) as exc:
        raise DataShapeError(f"cannot read D2PT export {source}: {exc}") from exc
    try:
        reference_raw = json.loads(reference.read_text(encoding="utf-8"))
    except (OSError, json.JSONDecodeError) as exc:
        raise DataShapeError(f"cannot read D2PT reference {reference}: {exc}") from exc
    builds = validate_builds(raw)
    reference_builds = validate_builds(reference_raw)
    total_matches = _total_matches(builds)
    reference_matches = _total_matches(reference_builds)
    if not reference_matches:
        raise DataShapeError("D2PT reference has no matches")
    total_match_delta = abs(total_matches - reference_matches) / reference_matches
    if total_match_delta > max_total_match_delta:
        raise DataShapeError(
            "D2PT total num_matches differs from reference by "
            f"{total_match_delta:.1%} (limit {max_total_match_delta:.1%})"
        )
    _atomic_json_write(output, builds)
    return {
        "heroes": len(builds),
        "populated_positions": sum(len(positions) for positions in builds.values()),
        "total_matches": total_matches,
        "total_match_delta": total_match_delta,
    }
